apiVersion: apps/v1
kind: Deployment   # 定义pod对象
metadata:
  name: nginx-deployment  #元数据
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.8
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: nginx-vol
      volumes:
        - name: nginx-vol
          hostPath:
            path: " /root/nginx"
          #emtryDir: {}